version: '3.4'

networks:
  backend:
  frontend:

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile 
    networks:
      - backend
      - frontend
    ports:
      - "59101:59101"
      - "59102:59102"
    
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    networks:
      - backend
    ports:
      - "59103:59103"
      - "59104:59104"

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    networks:
      - backend
    ports:
      - "59105:59105"
      - "59106:59106"

  profileservice:
    image: ${DOCKER_REGISTRY-}profileservice
    build:
      context: .
      dockerfile: ProfileService/Dockerfile
    networks:
      - backend
    ports:
      - "59107:59107"
      - "59108:59108"

  redis:
    container_name: Redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - "59201:80"
      - "59202:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend
